### ISSUE TITLE
Proposal: Allow the user to add traefik middlewares in order to add IPWhitelist to services 

### ISSUE THREAD

**Issue by Mijago** [mother-of-all-self-hosting/mash-playbook#115]
Hello there!

We just wanted to set up a [traefik ipwhitelist](https://doc.traefik.io/traefik/middlewares/http/ipwhitelist/), and got it to work, too.
For this to work we need to do the following:
- Add a middleware to traefik 
- Add the middleware to the service(s)

I propose two working methods that provide this functionality. As an example, I will modify `roles/galaxy/nextcloud/templates/labels.j2` to add the IPWhitelist functionality to Nextcloud.

> Note: For the sake of keeping this issue simple, I used `{% if VARIABLE  is defined %} ` instead of adding the variable(s) to `roles/galaxy/nextcloud/defaults/main.yml`.

## 1. Proposal: Adding a NAME_container_labels_additional_middleware variable to register traefik middlewares
In this scenario we simply allow the modification of the `middlewares` variable. This is the most versatile variant, as it will allow us to add *every* middleware we may want to add in the future. I propose that we add this (or similar) functionality to all roles.
We will add `nextcloud_container_labels_additional_middleware`, which will simply be appended to the `middlewares` variable.

```j2
# We find this line in `roles/galaxy/nextcloud/templates/labels.j2`
{% set middlewares = [] %}

# The following lines are new:
{% if nextcloud_container_labels_additional_middleware is defined %}
{% set middlewares = middlewares + [nextcloud_container_labels_additional_middleware ] %}
{% endif %}
```

With this simple change I can do the following in our `vars.yaml`:
```yml
nextcloud_container_labels_additional_labels: |
  traefik.http.middlewares.mash-nextcloud-whitelist.ipwhitelist.sourcerange=172.23.0.0/24, 10.0.0.0/24, 192.168.160.0/24

nextcloud_container_labels_additional_middleware: mash-nextcloud-whitelist
```

That's it. Nextcloud now has a middleware that provides an IP Whitelist.
This can also be used to add any amount of different middlewares we want.

## 2. Proposal: Adding NAME_container_labels_ipwhitelist_sourcerange to allow a simplified and automated setting of the iprange
I will now describe a second scenario, just for sake of completion.
In this scenario we create a new variable `nextcloud_container_labels_ipwhitelist_sourcerange` in `roles/galaxy/nextcloud/templates/labels.j2`. Setting this variable automates the settings form the first proposal.

```j2
{% if nextcloud_container_labels_ipwhitelist_sourcerange is defined %}
traefik.http.middlewares.{{ nextcloud_identifier }}-whitelist.ipwhitelist.sourcerange={{nextcloud_container_labels_ipwhitelist_sourcerange}}
{% set middlewares = middlewares + [nextcloud_identifier + '-whitelist'] %}
{% endif %}
```

In the `vars.yml` we can now simply write:
```yml
nextcloud_container_labels_ipwhitelist_sourcerange: 172.23.0.0/24, 10.0.0.0/24, 192.168.160.0/24
```

The second approach may be a bit easier to use, but is not as versatile as the first approach. We could, however, use both approaches at the same time.

-----------------------

I think a change like Proposal 1 would be beneficial for the entire project as it will allow more finegrained control over traefik middlewares.

**Comment by spantaleev** [comment]
Being able to add additional labels is certainly very helpful. I prefer the versatile solution (Proposal 1).

However.. I think for some use-cases it might matter (more so than for others) at which position the additional middlewares are injected (before the system-defined ones; after the system-defined ones). Sometimes, it may even be convenient to disable the system-defined middlewares or to inject a new middleware before, after or inbetween them.

Ideally, the solution would be flexible enough to support all these use-cases. I believe we should have a variable containing all middlewares for a given service (e.g. `nextcloud_container_labels_traefik_http_middlewares`), which is a combination of 3 other variables:
- `nextcloud_container_labels_traefik_http_middlewares_default` - a list of default middlewares defined by the role (dynamically-generated based on other role variables)
- `nextcloud_container_labels_traefik_http_middlewares_auto` - a list of middlewares defined by the playbook that wraps the role. I can't think of any need for this one, but there may be some cases where it's useful
- `nextcloud_container_labels_traefik_http_middlewares_custom` - a list of middlewares that people can define themselves

Each middleware definition in the list would ideally be defined by 2 things: the **middleware configuration** data and the **priority**. The playbook would sort all these middlewares by priority when deciding how to order them here: `traefik.http.routers.{{ nextcloud_identifier }}.middlewares=...`

This is similar to how services are defined and stopped/started by the [com.devture.ansible.role.systemd_service_manager](https://github.com/devture/com.devture.ansible.role.systemd_service_manager) role. Each service definition has a `priority` value.

Redoing it this way means that:
- middleware definitions would need to move to `nextcloud_container_labels_traefik_http_middlewares_default` in `defaults/main.yml`, not in the `templates/labels.j2` file - some redoing is necessary. See an example below.
- spewing out the middleware definitions in `templates/labels.j2` will be a simple loop over `nextcloud_container_labels_traefik_http_middlewares`
- `traefik.http.routers.{{ nextcloud_identifier }}.middlewares={{ nextcloud_container_labels_traefik_http_middlewares | sort (attribute='priority,name') | map(attribute='name') }}` - this needs to be redone like this, so that it sorts the list of middlewares by `priority` and merely output middleware names

Example middleware definitions for the Nextcloud role:

```yml
nextcloud_container_labels_traefik_http_middlewares: "{{ nextcloud_container_labels_traefik_http_middlewares_default + nextcloud_container_labels_traefik_http_middlewares_auto + nextcloud_container_labels_traefik_http_middlewares_custom }}"

nextcloud_container_labels_traefik_http_middlewares_default: |
  {{
    ([{
      'priority': 1000,
      'name': (nextcloud_identifier + '-slashless-redirect'),
      'type': 'redirectregex',
      'config': {
        'regex': '^(' + nextcloud_container_labels_traefik_path_prefix | quote + ')$',
        'replacement': '${1}/',
      },
    }] if nextcloud_container_labels_traefik_path_prefix != '/' else [])
    
    +
    
    ([{
      'priority': 2000,
      'name': (nextcloud_identifier + '-dav-redirectregex'),
      'type': 'redirectregex',
      'config': {
        'permanent': 'true',
        'regex': ('^' + nextcloud_scheme + '://' + nextcloud_hostname | quote + '/.well-known/(?:card|cal)dav$'),
        'replacement': (nextcloud_scheme + '://' + nextcloud_hostname + '/remote.php/dav/'),
      },
    }] if nextcloud_container_labels_traefik_dav_redirect_regex_enabled else [])
    
    +
    
    ([{
      'priority': 3000,
      'name': (nextcloud_identifier + '-strip-prefix'),
      'type': 'stripprefix',
      'config': {
        'prefixes': nextcloud_container_labels_traefik_path_prefix,
      },
    }] if nextcloud_container_labels_traefik_path_prefix != '/' else [])
    
    +
    
    ([{
      'priority': 4000,
      'name': (nextcloud_identifier + '-add-request-headers'),
      'type': 'headers',
      'config': {
        'customrequestheaders.key': 'value - TODO',
        'customrequestheaders.another_key': 'value - TODO',
      },
    }] if nextcloud_container_labels_traefik_additional_request_headers.keys() | length > 0 else [])
    
    +
    
    ([{
      'priority': 5000,
      'name': (nextcloud_identifier + '-add-response-headers'),
      'type': 'headers',
      'config': {
        'customresponseheaders.key': 'value - TODO',
        'customresponseheaders.another_key': 'value - TODO',
      },
    }] if nextcloud_container_labels_traefik_additional_response_headers.keys() | length > 0 else [])
  }}

nextcloud_container_labels_traefik_http_middlewares_auto: []

nextcloud_container_labels_traefik_http_middlewares_custom: []
```

This example definition requires more work around the last 2 default middlewares (dealing with headers). We need to loop over the headers hashmap and generate the `config` for the middlewares properly. This will require some more hacky Jinja syntax, but should be possible to do.

Redoing all roles like this will definitely take some time and effort. Looks like the Nextcloud role is almost at the finish line, except for the hacky Syntax for the last 2 default middlewares and for testing it all.

-----

The alternative is to do something similar to Proposal 1, but easier and not so flexible.

Perhaps just `_before` and `_after` middleware lists would be enough? The lists could only deal with "middleware names" with the goal of influencing the value of `traefik.http.routers.{{ nextcloud_identifier }}.middlewares=...`.

The actual middleware definitions can be injected by people manually via the "additional labels" variables (e.g. `nextcloud_container_labels_additional_labels`) which are already part of our roles.

**Comment by Mijago** [comment]
I think for the sake of simplicity, something like `_before` and `_after` would be easier to use. Adding the middleware itself via labels is probably easier to understand and to describe in the wiki.
Also, adding this concept to every role will be way faster than the alternative - basically a simple copy & paste for most services.

What would be the benefit of the proposed `nextcloud_container_labels_traefik_http_middlewares_default` over adding the middlewares as labels and using `_default`, `_before` and `_after`  to add middleware names? While it adds a lot of flexibility, it also seems to introduce a high degree of complexity.

**Comment by spantaleev** [comment]
The benefit of the more complex solution is that it allows people to inject a middleware anywhere in the list of default middlewares, not just "before" or "after".

Whether this is useful in practice to justify going for the complex solution.. I'm not sure. Likely not.

**Comment by Mijago** [comment]
Another alternative to allow us to add middlewares on any position is to introduce a `priority` field and sort the middleware list accordingly. 
This way, we can give the default services a default priority with large steps between them, e.g. 10, 20, 30, etc. These should be modifiable with their own variable, too.

Later on, we could do something like this in our `vars.yaml`:

```yaml
nextcloud_container_labels_traefik_middlewares_custom:
    - name: some-custom-middleware
      priority: 1
    - name: another-custom-middleware
      priority: 500
```

I think this could be a good middle ground:
- We can add our own middlewares
- We can add the middlewares at any position
- We do not introduce a lot of complexity upon the structure
