### ISSUE TITLE
Docker compose example for Ansible

### ISSUE THREAD

**Issue by MulverineX** [mother-of-all-self-hosting/mash-playbook#128]
https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/ansible.md#running-ansible-in-a-container-on-the-server-itself this only provides a docker run command, which tooling like Dockge unsuccessfully attempts to convert.

```yml
version: "3.3"
services:
  ansible:
    stdin_open: true
    tty: true
    privileged: true
    pid: host
    working_dir: /work
    volumes:
      - "`pwd`:/work"
    entrypoint:
      - /bin/sh
    image: docker.io/devture/ansible:2.14.5-r0-0
networks: {}
```
```
validating /opt/stacks/ansible/compose.yaml: volumes Additional property `pwd` is not allowed
```

Ideally, the guide would include a working example for docker compose
