### ISSUE TITLE
Woodpecker CI server hosted at subpath

### ISSUE THREAD

**Issue by sergiodj** [mother-of-all-self-hosting/mash-playbook#151]
Hi,

According to https://github.com/woodpecker-ci/woodpecker/issues/1636 (and https://github.com/woodpecker-ci/woodpecker/commit/b90e7904a56e171f82cc79595f037e76bdaec41d), it seems that it should now be possible to run Woodpecker CI at its own subpath.  I decided to give it a try but I'm still seeing problems with the setup.

Here are the `mash-traefik` logs:

```
[21/Feb/2024:03:19:35 +0000] "GET /ci/ HTTP/2.0" 200 857 "-" "-" 65 "mash-woodpecker-ci-server@docker" "http://172.20.0.4:8000" 0ms
[21/Feb/2024:03:19:35 +0000] "GET /assets/custom.css HTTP/2.0" 404 0 "-" "-" 69 "mash-forgejo@docker" "http://172.20.0.3:3000" 0ms
[21/Feb/2024:03:19:35 +0000] "GET /assets/index-u3ngPXwk.css HTTP/2.0" 404 0 "-" "-" 68 "mash-forgejo@docker" "http://172.20.0.3:3000" 1ms
[21/Feb/2024:03:19:35 +0000] "GET /assets/index-XiIDA5Cc.js HTTP/2.0" 404 0 "-" "-" 67 "mash-forgejo@docker" "http://172.20.0.3:3000" 1ms
[21/Feb/2024:03:19:35 +0000] "GET /assets/custom.js HTTP/2.0" 404 0 "-" "-" 70 "mash-forgejo@docker" "http://172.20.0.3:3000" 0ms
[21/Feb/2024:03:19:35 +0000] "GET /web-config.js HTTP/2.0" 404 11 "-" "-" 66 "mash-forgejo@docker" "http://172.20.0.3:3000" 8ms
[21/Feb/2024:03:19:35 +0000] "GET /assets/index-u3ngPXwk.css HTTP/2.0" 404 0 "-" "-" 71 "mash-forgejo@docker" "http://172.20.0.3:3000" 0ms
[21/Feb/2024:03:19:35 +0000] "GET /assets/custom.css HTTP/2.0" 404 0 "-" "-" 72 "mash-forgejo@docker" "http://172.20.0.3:3000" 0ms
[21/Feb/2024:03:19:35 +0000] "GET /assets/custom.js HTTP/2.0" 404 0 "-" "-" 73 "mash-forgejo@docker" "http://172.20.0.3:3000" 0ms
```

The problem seems to happen because the first request goes to the right container, but the subsequent requests (without the `/ci/` prefix) are going to the wrong container (Forgejo, in this case).

It's not clear to me if this is a problem with the playbook, Woodpecker, or both, but I decided to start by filing a bug here.

**Comment by sergiodj** [comment]
Here's my config, btw:

```yaml
devture_woodpecker_ci_server_enabled: true

devture_woodpecker_ci_server_hostname: 'forgejo.domain'

# Generate this secret with `openssl rand -hex 32`
devture_woodpecker_ci_server_config_agent_secret: 'nope'

devture_woodpecker_ci_server_path_prefix: /ci
devture_woodpecker_ci_server_config_open: false

# Add one or more usernames that match your version control system (e.g. Gitea) below.
# These users will have admin privileges upon signup.
devture_woodpecker_ci_server_config_admins:
  - MYSELF

devture_woodpecker_ci_server_provider: gitea

# devture_woodpecker_ci_server_gitea_server specifies the URL to the Gitea server.
# Example: https://woodpecker-ci.org/docs/administration/vcs/gitea#woodpecker_gitea_url
devture_woodpecker_ci_server_config_gitea_url: '{{ forgejo_config_root_url }}'

devture_woodpecker_ci_server_config_gitea_client: 'nope'
devture_woodpecker_ci_server_config_gitea_secret: 'nope'

devture_woodpecker_ci_server_container_add_host_domain_name: "{{ forgejo_hostname }}"
devture_woodpecker_ci_server_container_add_host_ip_address: "{{ ansible_host }}"
```
