### ISSUE TITLE
gitea_container_additional_networks_custom variable is not used/working

### ISSUE THREAD

**Issue by Bergruebe** [mother-of-all-self-hosting/mash-playbook#171]
Hi,
I'm trying to use the mash-exim-relay in Gitea. After realizing that they are not in the same network, I tried to add Gitea to the `mash-exim-relay`-network with the `gitea_container_additional_networks_custom` variable. => this is not working.

Somehow the custom variable is not used in the run of the playbook. I tested it by adding 
```yaml
- name: Debug custom network configuration
  debug:
    msg: "Error: custom: {{ gitea_container_additional_networks_custom }}  all: {{ gitea_container_additional_networks }}"
```
at the end of [`roles/gitea/tasks/install.yml`](https://github.com/mother-of-all-self-hosting/ansible-role-gitea/blob/main/tasks/install.yml). 

The custom networks is not added to  `gitea_container_additional_networks`, like it is configured [here (`ansible-role-gitea/defaults/main.yml`)](https://github.com/mother-of-all-self-hosting/ansible-role-gitea/blob/ee522640f49d310ea4227f0e9f835e5029d9b3a9/defaults/main.yml#L118-L124 ):

```yaml
# A list of additional container networks that the container would be connected to.
# The playbook does not create these networks, so make sure they already exist.
gitea_container_additional_networks: "{{ gitea_container_additional_networks_auto + gitea_container_additional_networks_custom }}"
# gitea_container_additional_networks_auto is reserved for usage by the playbook.
# Your custom networks should go into gitea_container_additional_networks_custom.
gitea_container_additional_networks_auto: []
gitea_container_additional_networks_custom: []
```

Sadly I couldn't get further with my debugging, because I don't understand how you are managing the variables in this playbook. (*Maybe a developer documentation would help 😀*)

Btw: I also tried it the other way round to add exim-relay to the gitea network, which also didn't work, see [this PR](https://github.com/mother-of-all-self-hosting/ansible-role-exim-relay/pull/1).
