### ISSUE TITLE
[mash-uptime-kuma] Touble using Docker monitor connect EACCES /var/run/docker.sock

### ISSUE THREAD

**Issue by rdaries** [mother-of-all-self-hosting/mash-playbook#24]
Hello,

fairly simple issue, i installed uptime kuma using mash playbook, it works well, now i'd like to try the docker monitoring to monitor the machine hosting uptime kuma and other docker containers but when i try to set it up i got this error `Connect EACCES /var/run/docker.sock`

how to allow uptime kuma to connect it?

```yaml
#######################################################################
#                                                                      #
# uptime-kuma                                                          #
#                                                                      #
########################################################################

uptime_kuma_enabled: true
uptime_kuma_hostname: up.example.com

uptime_kuma_container_extra_arguments:
  - '--env "PGID=1006"'
  - '--env "PUID=996"'
  - '-v /var/run/docker.sock:/var/run/docker.sock'

########################################################################
#                                                                      #
# /uptime-kuma                                                         #
#                                                                      #
########################################################################
```

Source [How to Monitor Docker Containers](https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers)
