### ISSUE TITLE
Traefik: Proxy an external service?

### ISSUE THREAD

**Issue by oliverlorenz** [mother-of-all-self-hosting/mash-playbook#309]
Hey!

is there any way to configure a simple proxy to an external service? For example provide `my.example.com` to an IPv6 or something. Background: I have a running service on a Raspberry Pi in my apartment and want to expose them under a domain.

Any ideas? 🙂

**Comment by spatterIight** [comment]
It is possible to due this with the Traefik role -> https://github.com/mother-of-all-self-hosting/ansible-role-traefik

By using the AUX role you can place a file which will configure the necessary router, service, and etc.

Something like this:

```yaml
devture_traefik_configuration_extension_yaml: |
  providers:
    file:
      directory: /config/
      watch: true
      filename: ""
  serversTransport:
    insecureSkipVerify: true

aux_file_definitions:
  - dest: "{{ devture_traefik_config_dir_path }}/spatterlight.space.yml"
    content: |
      http:
        routers:
          spatterlight-router:
            rule: Host(`spatterlight.space`)
            service: spatterlight-service
            entryPoints:
              - web-secure
            tls:
              certResolver: default
        services:
          spatterlight-service:
            loadBalancer:
              servers:
                - url: "http://172.24.16.2:2398"
    owner: "traefik"
    group: "traefik"
```
