### ISSUE TITLE
Can't connect Nextcloud client

### ISSUE THREAD

**Issue by estribiyo** [mother-of-all-self-hosting/mash-playbook#349]
Trying to setup Nextcloud, I'm having issues with client connection and don't know where to start to solve the problem.

This is the configuration used:

```
########################################################################
#                                                                      #
# postgres                                                             #
#                                                                      #
########################################################################
postgres_enabled: true
postgres_connection_password: YYYYYYYYYYYYYYYYYYYYYYYYY
postgres_managed_databases_additional:
  - name: nextcloud
    username: nextcloud
    password: XXXXXXXXXXXXXXXXXXXXXXX
########################################################################
#                                                                      #
# /postgres                                                            #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# nextcloud                                                            #
#                                                                      #
########################################################################
nextcloud_enabled: true
nextcloud_hostname: nc.mydomain.com
nextcloud_url: {nextcloud_hostname}
nextcloud_database_password: XXXXXXXXXXXXXXXXXXXXXXX
nextcloud_database_type: postgres
nextcloud_database_hostname: mash-postgres
nextcloud_database_name: nextcloud
nextcloud_database_username: nextcloud
########################################################################
#                                                                      #
# /nextcloud                                                           #
#                                                                      #
########################################################################
```

When connecting the desktop client, it complains about:

```
The polling URL does not start with HTTPS despite the login URL started wit HTTPS. 
Login will not be possible because this might be a security issue. 
Please contact yout administrator.
```

What can I do? Don't know where to look. I supose that's something about Traefik but looking at the documentation I don't see nothing. Could be something that I've missed? What logs can help me?

Tank you in advance.

**Comment by spantaleev** [comment]
Is that everything in your `vars.yml`?

Looks like there's no reverse-proxy (Traefik).

I suggest that you start with the example vars seen in [examples/vars.yml](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/ffab60f66ed150268128bc0cb60670ee121e2ad7/examples/vars.yml) and just add more stuff at the end.

----------

Why are you overriding `nextcloud_url`?

By default, it's define like this:

```yml
nextcloud_url: "{{ nextcloud_scheme }}://{{ nextcloud_hostname }}{{ nextcloud_path_prefix }}"
```

.. and is a valid URL like: `https://nc.mydomain.com/`.

You've set it to just a hostname, it seems.

--------

You don't need to assign database passwords manually. There's also no need to use `postgres_managed_databases_additional`.

The playbook does all that for you.

------------------

It seems like you're making things harder than you should. As [our documentation in `docs/services/nextcloud.md`](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/services/nextcloud.md) says, you only need something like this:

```yml
########################################################################
#                                                                      #
# nextcloud                                                            #
#                                                                      #
########################################################################

nextcloud_enabled: true

nextcloud_hostname: mash.example.com
nextcloud_path_prefix: /nextcloud

# Valkey configuration, if you wish to improve performance.
# You can start without it though.

########################################################################
#                                                                      #
# /nextcloud                                                           #
#                                                                      #
########################################################################
```

Of course, you also need to enable Traefik and Postgres, as per the example `vars.yml` file.
