### ISSUE TITLE
New Authentik installation: can not connect to redis & can not uninstall

### ISSUE THREAD

**Issue by Mijago** [mother-of-all-self-hosting/mash-playbook#47]
Greetings!

I wanted to test and validate the new Authentik changes.

While doing so, I ran into two issues:
1. neither worker nor service can not connect to the redis (using the default redis right from the configuration). I verified that redis is running and open for connections (using `journalctl -fu mash-redis.service`).
2. When disabling authentik, you run into another issue: It can not find `authentik_frontend_identifier` and thus fails when it tries to remove it.

Sadly I do not have the time to troubleshoot right now, but I wanted to let you know about this issue nonetheless.

# Config

```yaml
########################################################################
#                                                                      #
# redis                                                                #
#                                                                      #
# Required for Authentik                                               #
########################################################################

redis_enabled: true

########################################################################
#                                                                      #
# /redis                                                               #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# authentik                                                            #
#                                                                      #
########################################################################

authentik_enabled: true
authentik_hostname: auth.DOMAIN.net
authentik_secret_key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

# Base configuration as shown above

# Point authentik to the shared Redis instance
authentik_config_redis_hostname: "{{ redis_identifier }}"

# Make sure the authentik service (mash-authentik.service) starts after the shared Redis service (mash-redis.service)
authentik_systemd_required_services_list_custom:
  - "{{ redis_identifier }}.service"

# Make sure the authentik container is connected to the container network of the shared Redis service (mash-redis)
authentik_container_additional_networks_custom:
  - "{{ redis_identifier }}"


########################################################################
#                                                                      #
# /authentik                                                           #
#                                                                      #
########################################################################
```

# 1. Errors after starting
Neither worker nor server can connect to the redis, and thus can not start (and spam the logs).

`> sudo journalctl -fu mash-authentik-worker.service`
```
Apr 23 12:05:18 matrix mash-authentik-worker[1103356]: {"event": "Redis Connection failed, retrying... (Error -2 connecting to mash-redis:6379. Name or service not known.)", "level": "info", "logger": "authentik.lib.config", "timestamp": 1682244318.5348532, "redis_url": "redis://:@mash-redis:6379/0"}
```

# 2. Error after disabling redis and authentik:

When disabling authentik, you get another error, which stops the entire playbook to setup and start things.
This stays over multiple runs of the command (one can hope, right?).

`> ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start`
```
TASK [galaxy/authentik : Ensure authentik services are stopped and removed] *********************************************************************************************************
fatal: [DOMAIN.net]: FAILED! => {"msg": "'authentik_frontend_identifier' is undefined"}
```
