### ISSUE TITLE
Invalid YAML in `docs/services/promtail.md`

### ISSUE THREAD

**Issue by spatterIight** [mother-of-all-self-hosting/mash-playbook#570]
In `docs/services/promtail.md` the definition of `promtail_config_scrape_configs_custom` is not valid YAML:

```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in 'vars.yml': line 202, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - localhost
      __path__: /data/ssh
              ^ here
```

I believe the correct definition is:

```yaml
promtail_config_scrape_configs_custom:
  - job_name: ssh
    static_configs:
      - targets: ["localhost"]
        __path__: /data/ssh
        labels:
          job: ssh
```

**Comment by spatterIight** [comment]
My proposed corrected definition may still be invalid:

```
May 21 18:54:05 dev promtail[97840]: Unable to parse config: /etc/promtail/config.yml: yaml: unmarshal errors:
May 21 18:54:05 dev promtail[97840]:   line 8: field __path__ not found in type struct { Targets []string "yaml:\"targets\""; Labels model.LabelSet "yaml:\"labels\"" }. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```

I am investigating.

**Comment by spatterIight** [comment]
I think this is the correct variable: 

```yaml
promtail_config_scrape_configs_custom:
  - job_name: ssh
    static_configs:
      - targets: ["localhost"]
        labels:
          job: ssh
          __path__: /data/ssh

```

Will make PR later
