### ISSUE TITLE
Add Forgejo Support

### ISSUE THREAD

**Issue by heliophane** [mother-of-all-self-hosting/mash-playbook#60]
Forgejo is a fork of Gitea created by Codeberg that is designed to be a drop in replacement for Gitea.
https://forgejo.org/

**Comment by spantaleev** [comment]
Using the [Gitea role](https://github.com/mother-of-all-self-hosting/ansible-role-gitea) and overriding a few variables in your `vars.yml` file should work.

Most importantly, you should override the `gitea_container_image` variable: https://github.com/mother-of-all-self-hosting/ansible-role-gitea/blob/a75e575ecdec6a734e772b9df94d24dc54f1fb7f/defaults/main.yml#LL19C1-L19C112

Perhaps this way:

```yaml
# Not strictly necessary to override these, but it prevents confusion
gitea_identifier: "{{ mash_playbook_service_identifier_prefix }}forgejo"
gitea_base_path: "{{ mash_playbook_base_path }}/{{ mash_playbook_service_base_directory_name_prefix }}forgejo"
gitea_config_database_name: forgejo
gitea_config_database_username: forgejo

gitea_container_image: codeberg.org/forgejo/forgejo:1.19.3-0
```

I haven't given it a try. If you do and this works well for you, we can document this on our `gitea.md` documentation page and possibly by creating a new `forgego.md` page which links to `gitea.md#using-forgejo`

At some point, it may make sense to fork the role, but for now it doesn't seem like there are any practical differences between Gitea and Forgejo and it doesn't seem like there's a good reason to go for Forgejo just yet (unless one has appeared and I don't know about it yet).

**Comment by jahanson** [comment]
I wanted to get forgejo running with all of the mash backup addons but I ran into some permissions issues from a fresh install. Any recommendations? 

## Logs
![image](https://github.com/mother-of-all-self-hosting/mash-playbook/assets/1548511/484097b1-ccc0-454e-b1e5-2a9346ac0440)

## My config
```yaml
########################################################################
#                                                                      #
# gitea--forgejo                                                       #
#                                                                      #
########################################################################

gitea_enabled: true
gitea_hostname: git.hsn.dev
# Not strictly necessary to override these, but it prevents confusion
gitea_identifier: "{{ mash_playbook_service_identifier_prefix }}forgejo"
gitea_base_path: "{{ mash_playbook_base_path }}/{{ mash_playbook_service_base_directory_name_prefix }}forgejo"
gitea_config_database_name: forgejo
gitea_config_database_username: forgejo

gitea_container_image: codeberg.org/forgejo/forgejo:1.20.2-0

########################################################################
#                                                                      #
# /gitea--forgejo                                                      #
#                                                                      #
########################################################################
```
