### ISSUE TITLE
Collabora page is blank showing only an "OK"

### ISSUE THREAD

**Issue by aik2mlj** [mother-of-all-self-hosting/mash-playbook#89]
Hi! I just did a mash setup with nextcloud, redis and collabora on a fresh ubuntu 22.04 vm. The collabora page only returns a blank page with "OK" on it and nothing else. And I cannot open document files in nextcloud office after running the command `just run-tags install-nextcloud-app-collabora`.

![image](https://github.com/mother-of-all-self-hosting/mash-playbook/assets/53085155/fb98ce04-f28a-40a4-84d4-d14de4e1f213)

Here is my `var.yml`:
```yaml
########################################################################
#                                                                      #
# nextcloud                                                            #
#                                                                      #
########################################################################

nextcloud_enabled: true

nextcloud_hostname: cloud.mydom.com

nextcloud_redis_hostname: "{{ redis_identifier }}"

nextcloud_systemd_required_services_list_custom:
  - "{{ redis_identifier }}.service"

nextcloud_container_additional_networks_custom:
  - "{{ redis_identifier }}"

nextcloud_collabora_app_wopi_url: "{{ collabora_online_url }}"

########################################################################
#                                                                      #
# /nextcloud                                                           #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# redis                                                                #
#                                                                      #
########################################################################

redis_enabled: true

########################################################################
#                                                                      #
# /redis                                                               #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# collabora-online                                                     #
#                                                                      #
########################################################################

collabora_online_enabled: true

collabora_online_hostname: collabora.mydom.com

collabora_online_env_variable_password: 'mypasswd'

collabora_online_aliasgroup: "https://{{ nextcloud_hostname | replace('.', '\\.') }}:443"

########################################################################
#                                                                      #
# /collabora-online                                                    #
#                                                                      #
########################################################################
```
